services:
  # server:
  #   image: go_app
  #   container_name: rest_api_server
  #   build:
  #     context: ../
  #     dockerfile: build/Dockerfile
  #   command: ./rest_api -env docker
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db

  db:
    image: postgres:16
    container_name: local_pgdb
    # restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin # pragma: allowlist secret
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    # restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: raj@nola.com
      PGADMIN_DEFAULT_PASSWORD: admin # pragma: allowlist secret
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
